---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.18.0
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    prometheus:
      enable: true
    worker:
      config:
        core:
          sources: ["pci", "system", "usb"]
          # sources: ["custom", "pci", "usb", "system"]
        # sources:
        #   usb:
        #     deviceClassWhitelist: ["02", "03", "0e", "ef", "fe", "ff"]
        #     deviceLabelFields: ["class", "vendor", "device"]
