---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: vaultwarden-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ADMIN_TOKEN: "{{.ADMIN_TOKEN}}"
        SMTP_FROM: "{{.SMTP_FROM}}"
        SMTP_FROM_NAME: Passwords
        SMTP_USERNAME: "{{.SMTP_USERNAME}}"
        SMTP_PASSWORD: "{{.SMTP_PASSWORD}}"
        SMTP_HOST: "{{.SMTP_HOST}}"
        SMTP_PORT: "{{.SMTP_PORT}}"
        SMTP_SECURITY: starttls
  dataFrom:
    - extract:
        key: vaultwarden
    - extract:
        key: smtp

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName vaultwarden-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: *secretName
    template:
      type: Opaque
      data:
        DATABASE_URL: '{{ index . "uri" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-vaultwarden