---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: qbittorrent-loki-rules
    files:
      - qbittorrent.yaml=./resources/lokirule.yaml
    options:
      labels:
        loki_rule: 'true'
  - name: qbittorrent-scripts
    files:
      - scripts/xseed.sh
      - scripts/post-process.sh
  - name: qbittorrent-coredns
    files:
      - ./config/Corefile
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
configurations:
  - kustomizeconfig.yaml
