---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flaresolverr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: flaresolverr
  values:
    controllers:
      flaresolverr:
        containers:
          app:
            image:
              repository: ghcr.io/flaresolverr/flaresolverr
              tag: v3.4.3@sha256:057eedf25a22905685c55be78b2dd70bcd617a921384cd17cb3f4e8901753331
            env:
              CAPTCHA_SOLVER: "harvester"
            resources: {}
            # requests:
            #   cpu: 10m
            #   memory: 150Mi
            # limits:
            #   memory: 500Mi
    service:
      app:
        controller: flaresolverr
        ports:
          http:
            port: 8191
