apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-rbd-node
  namespace: rook-ceph
type: kubernetes.io/rook
data:
  userID: ENC[AES256_GCM,data:EpAFG18TJevrkSXediSmjA==,iv:HOAtSiHwQjLS+6yGTjNSt+R9hL/ytuMXch1XeLMFTXw=,tag:NHLlgANjJwtCrKX4WUlgRQ==,type:str]
  userKey: ENC[AES256_GCM,data:zMaBJiVDn+SSOjlOnN++ra5zy1EcY+j3E034+1tYWm/1lXT7SsnFQCLBKiJ3zmJ6FmXjFz18sU8=,iv:j5v/A4y4fVDcrknMn7GGBl9RLnBCwn7sNvVMaVaIvkM=,tag:Yovmg1AHgkQh0sLPEPxnJQ==,type:str]
sops:
  age:
    - recipient: age1h2p8ckzxnxj7gvav9remh2nrgw6tfrgna0a62en5j8tglvuca9vq7uajxz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSlJYYU5lRmVWbUlYZG9q
        bWpTcm1rY0pGOTVmcGl5SnZGb2JqcFA3VGhrClFyd3JHL3hqa3dyZUhWa014ZDdw
        bGoxVjgrazF4UmRCM3hoN0ZzbVZTYTAKLS0tIDR6ZDRudFdxWEN5WFF1dU03Q1NQ
        MnE3bXd4WE1BOTU4TG1IY0pLVHhuWm8K21sPb4/bujMgbfuougm63fclLHca+ASM
        l+6ywjh5o9R3ImYZjx/Hp/7fA54y/KPIwdsEoJjWekNzGDOTdSwmTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-20T12:04:37Z"
  mac: ENC[AES256_GCM,data:S1w/ERoMqUTHy8VIEwJYWfhmczyXUQIniRtY5njwe9JyiL0hyuWqGJ1+p9lX3yyM+GpVcLoy9QoRSt4HHqRGddHf9m1qgJB3mIiKkjsEz0WcpJPpEh5U4LneZn4k/CG0qKHtj03x18BcfT5sPObT1lS9FbQ6Lm3IdAskptm23Mc=,iv:dhSr2napTHXQYcTT4A8SKBpwR8nLQTQWzTGJb5vsQuI=,tag:ma44RsjnVNltOx0sNFI9YQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
