apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-cephfs-provisioner
  namespace: rook-ceph
type: kubernetes.io/rook
data:
  adminID: ENC[AES256_GCM,data:hkwS7OY8x52mE14XjBG9NYatKyVeX6znT2NnIoXbBzc=,iv:3rpUh1kqJSTtStN+Fw24DssOKziHVch4zJ8a65noKkU=,tag:+3oYKB7wVToggal/WX8dHw==,type:str]
  adminKey: ENC[AES256_GCM,data:cBTIF/oSdS/0OdMLgzS3dSyQ2/5FuJt9oiQ7WWllS48H0mCGJllwoCGp5+Q5f/sO2rIql0g4ll4=,iv:UdyH9zA2pXqRvrXO1Z6VpyuYPRVH8+/qpMRyxI5GGjU=,tag:vP99hdTL2RD+6o/0dPt1Ug==,type:str]
sops:
  age:
    - recipient: age1h2p8ckzxnxj7gvav9remh2nrgw6tfrgna0a62en5j8tglvuca9vq7uajxz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VkZvbS90L240ekN6RXZI
        K2FOZXJieTB3WGg3TVNwR2ZrTEJlakdWdXlRCngrd0craXJlS2NqZ1JUWHFCL0po
        WU1QWmRJMVJQbkRwOXNYYzQ0R1BCc2sKLS0tIEQ5dVEyTVByNmhscjB1TnM4VjFn
        aTJIZFhmZjlIYkVxNWtxT0s4MVpSMnMK1TUA0DNjOdDWj5cZCVLWNy98e8E90hLr
        fHYAyLYYNqnQXYVJClNvkHYfIs7psm5xAONa85rLYk3UoXN7IRiegw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-20T12:04:27Z"
  mac: ENC[AES256_GCM,data:Lo5+WEkgZqRZCsWaObJaCjsZSKysDkPp2yEpiSbBEnFyvJqjG+VJu4EcFxtkpL5KRkx3ZtSX/4ZpwMlwyTQQW9OW6d3kgdwb4U9NYzhzQdKLxPeowJ8B6eOnT0BGH8yFMRSYSd7Qse7vLL50lK8iaTgEb4bxwqGyCn7bAn0DLk0=,iv:TsH8ezjOAHCYyMK0ob1kMgUE+wGZvnusBOzE2mdIbwQ=,tag:8P5k8YU28MxchHkVDmubVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
