---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shlink
spec:
  dependsOn:
    - name: crunchy-postgres-operator-cluster
      namespace: database
    - name: onepassword
      namespace: external-secrets
  interval: 30m
  path: ./kubernetes/apps/default/shlink/app
  postBuild:
    substitute:
      APP: shlink
      GATUS_SUBDOMAIN: ln
      GATUS_PATH: /AtAO0
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
  retryInterval: 1m
  timeout: 5m
