---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app home-assistant
  namespace: flux-system
spec:
  components:
    - ../../../../components/volsync
    - ../../../../components/gatus/external
    - ../../../../components/nfs-scaler
  dependsOn:
    - name: onepassword
      namespace: external-secrets
    - name: crunchy-postgres-operator-cluster
      namespace: database
  interval: 30m
  path: ./kubernetes/apps/home-automation/home-assistant/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: home
      VOLSYNC_CAPACITY: 10Gi

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: home-automation
  wait: false
  retryInterval: 1m
  timeout: 5m