---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName artifact-keeper-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secretName
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .JWT_SECRET }}"
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        MEILI_MASTER_KEY: "{{ .MEILI_MASTER_KEY }}"
        MEILISEARCH_API_KEY: "{{ .MEILI_MASTER_KEY }}"
  dataFrom:
    - extract:
        key: artifact-keeper

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName artifact-keeper-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: *secretName
    template:
      type: Opaque
      data:
        DATABASE_URL: '{{ index . "uri" }}?sslmode=disable'
  dataFrom:
    - extract:
        key: postgres-pguser-artifact-keeper
