---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app outline
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: crunchy-postgres-operator-cluster
      namespace: database
    - name: onepassword
      namespace: external-secrets
    - name: dragonfly-cluster
      namespace: database
  interval: 30m
  path: ./kubernetes/apps/default/outline/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: docs
      VOLSYNC_CLAIM: *app
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_UID: "568"
      VOLSYNC_GID: "568"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
  retryInterval: 1m
  timeout: 5m
