---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  # Flux-Kustomizations
  # - ./kubernetes-schemas/ks.yaml
  - ./immich/ks.yaml
  - ./jellyfin/ks.yaml
  - ./stash/ks.yaml