---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gitea
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
    - ../../../../components/gatus/external
    - ../../../../components/keda/nfs-scaler
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: dragonfly-cluster
      namespace: database
  path: ./kubernetes/apps/default/gitea/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: *app
      VOLSYNC_ACCESSMODES: ReadWriteMany
      VOLSYNC_CAPACITY: 100Gi
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-filesystem
      VOLSYNC_STORAGECLASS: ceph-filesystem