---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gitea

spec:
  components:
    - ../../../../components/volsync
    - ../../../../components/gatus/external
    - ../../../../components/nfs-scaler
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: dragonfly-cluster
      namespace: database
  interval: 30m
  path: ./kubernetes/apps/default/gitea/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: *app
      VOLSYNC_ACCESSMODES: ReadWriteMany
      VOLSYNC_CAPACITY: 100Gi
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-filesystem
      VOLSYNC_STORAGECLASS: ceph-filesystem

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
  retryInterval: 1m
  timeout: 5m