---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName whisparr-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: *secretName
    template:
      type: Opaque
      data:
        WHISPARR__POSTGRES_HOST: '{{ index . "host" }}'
        WHISPARR__POSTGRES_PORT: '{{ index . "port" }}'
        WHISPARR__POSTGRES_USER: '{{ index . "user" }}'
        WHISPARR__POSTGRES_PASSWORD: '{{ index . "password" }}'
        WHISPARR__POSTGRES_MAIN_DB: '{{ index . "dbname" }}'
        # require manual update for second database like:
        # ALTER DATABASE "dbname-logs" OWNER TO "dbname"
        WHISPARR__POSTGRES_LOG_DB: '{{ index . "dbname" }}-logs'
  dataFrom:
    - extract:
        key: postgres-pguser-whisparr


---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName whisparr-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secretName
    template:
      type: Opaque
      data:
        WHISPARR__API_KEY: "{{ .WHISPARR_API_KEY }}"
        PUSHOVER_TOKEN: "{{ .PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
  dataFrom:
    - extract:
        key: arr
    - extract:
        key: pushover
