---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whisparr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: whisparr
  driftDetection:
    mode: enabled
  values:
    controllers:
      whisparr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/jfroy/whisparr-nightly
              tag: 2.0.0.987@sha256:fb192831a387029676fa25de3a304542a6c19ae0bd50b0d1ba51bb959d5e540a
            env:
              WHISPARR__ANALYTICS_ENABLED: "False"
              WHISPARR__AUTHENTICATION_METHOD: External
              WHISPARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              WHISPARR__BRANCH: develop
              WHISPARR__INSTANCE_NAME: Whisparr
              WHISPARR__LOG_LEVEL: info
              WHISPARR__PORT: &port 80
              TZ: Europe/Warsaw
            envFrom:
              - secretRef:
                  name: whisparr-secret
              - secretRef:
                  name: whisparr-db-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 10000
        seccompProfile: {type: RuntimeDefault}
    service:
      app:
        controller: whisparr
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.pospiech.dev"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    # https://github.com/h3mmy/bloopySphere/blob/main/cluster/apps/downloads/whisparr/helm-release.yaml
    persistence:
      config:
        existingClaim: whisparr
      tmp:
        type: emptyDir

      media:
        type: nfs
        server: nas01.internal
        path: /mnt/data/media
        globalMounts:
          - path: /media
            # pushover-notify:
            #   type: configMap
            #   name: whisparr-configmap
            #   defaultMode: 0775
            #   globalMounts:
            #     - path: /scripts/pushover-notify.sh
            #       subPath: pushover-notify.sh
            #       readOnly: true
            # media:
            #   type: nfs
            #   server: citadel.internal
            #   path: /mnt/storage0/media
            #   globalMounts:
            #     - path: /media
