apiVersion: v1
kind: Secret
metadata:
    name: qbtools-config-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:IeQujRqUuBgrMCKayWyOnh8=,iv:Ke3N+L6TiHe9Gj6VRO4LUJC/xOvNzGjmOUnbILfLZEQ=,tag:bJuqRfGSizTciVxZEnS0JQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ckjyhwwg56a0q2ddfctv49j95tzx8np7g2eelwyevdv5u4mg4frqr2cwl2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaXdZK3UzUDJMRDVkc1FT
            eGwvRHlYVG1TN211d1h5TVB0OThsK3QyMVRrCm5MVGRzdUVTb0o0YXJBOUIrdTlN
            dHkrTGxVZjczeHpQR0g5cG81cDIwLzgKLS0tIDhZcEoyVGdHdlNCRHpQTUMyZjBz
            TC9QSUphWHFyQzZYVzdDUXRLVzdtN1EK1mvRLdmyAsZOupgnM6N1KlsZDcUQithM
            i2XvMPBHja97cSOQL1gWs5Z19ptcWAvb6TKq6SM8Me2lr1kfQcKozg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-07T15:37:50Z"
    mac: ENC[AES256_GCM,data:xEmluKYwJxz06/0pQ+vowfyKwreKu8gKVELT1aVuY3xpGfo/8N2u8fsmzqGRa1NJ9yspTyIGUitxpZyalY+wR11GsI7fe5TWwqVxPl4oPNHebxUUybtyD/GogT4VnmCHO5Fusr38+olNScdOtv1bHG9/B25onTQpPGhF/UhXznw=,iv:DdOTHplbruo+ELAMWiM9Ql2bg8rGYWiGiReWFYHmX5Y=,tag:Fdtq9FlriRnQVYLZ5EkERg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
