---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName zot-users
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secretName
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        htpasswd: "{{ .HTPASSWD }}"
  dataFrom:
    - extract:
        key: zot-registry

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName zot-registry-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secretName
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        authHeader: "{{ .AUTH_HEADER }}"
  dataFrom:
    - extract:
        key: zot-registry
