---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: conbee-ii-zigbee
spec:
  rules:
    - # Conbee II
      name: conbee-ii-zigbee
      labels:
        feature.node.kubernetes.io/zigbee-controller: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
          # [502574.586957] usb 1-1.3: new full-speed USB device number 4 using xhci_hcd
          # [502574.695960] usb 1-1.3: New USB device found, idVendor=1cf1, idProduct=0030, bcdDevice= 1.00
          # [502574.695969] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
          # [502574.695974] usb 1-1.3: Product: ConBee II
          # [502574.695979] usb 1-1.3: Manufacturer: dresden elektronik ingenieurtechnik GmbH
          # [502574.695983] usb 1-1.3: SerialNumber: DE2452113
            vendor: { op: In, value: ["1cf1"] }
            device: { op: In, value: ["0030"] }
            # serial: { op: In, value: ["DE2452113"] }