---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app searxng

spec:
  components:
    - ../../../../components/gatus/internal
  dependsOn:
    - name: dragonfly-cluster
      namespace: database
  interval: 30m
  path: ./kubernetes/apps/llm/searxng/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: search

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: llm
  wait: false
  timeout: 5m