---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName opengist-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secretName
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OG_OIDC_CLIENT_KEY: "{{ .OIDC_CLIENT_ID }}"
        OG_OIDC_SECRET: "{{ .OIDC_CLIENT_SECRET }}"

  dataFrom:
    - extract:
        key: opengist
