---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: csi-driver-nfs
  values:
    controller:
      replicas: 1
    storageClass:
      create: false
      # name: nfs-default
      # parameters:
      #   server: nfs.homelab.pospiech.dev
      #   share: /volume1/homelab
      #   subdir: "$${pvc.metadata.namespace}-$${pvc.metadata.name}"
      # mountOptions:
      #   - nfsvers=4.2
      #   - nconnect=16
      #   - hard
      #   - noatime
      # reclaimPolicy: Delete
      # volumeBindingMode: Immediate
