---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wheel
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: wheel
  values:
    global:
      fullnameOverride: *app
    controllers:
      wheel:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          nodeSelector:
            kubernetes.io/arch: amd64
          imagePullSecrets:
            - name: zot-credentials
          annotations:
            secret.reloader.stakater.com/reload: "auto"
        containers:
          main:
            image:
              repository: registry.pospiech.dev/spin-the-wheel
              tag: RELEASE.2025-10-13T13-47-13Z
              pullPolicy: Always
            env:
              SERVER_PORT: &port 8080
              TZ: Europe/Warsaw

    service:
      wheel:
        enabled: true
        controller: *app

        ports:
          http:
            port: *port

    route:
      main:
        hostnames:
          - "wheel.pospiech.dev"
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: wheel
                port: *port
