---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app openspeedtest
  namespace: flux-system
spec:
  components:
    - ../../../../components/gatus/internal
  interval: 30m
  path: ./kubernetes/apps/default/openspeedtest/app
  postBuild:
    substitute:
      APP: *app

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
  retryInterval: 1m
  timeout: 5m