---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app shlink-api
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 1
        annotations:
          secret.reloader.stakater.com/reload: shlink-secret,shlink-db-secret

        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app

        containers:
          main:
            image:
              repository: ghcr.io/shlinkio/shlink
              # yamllint disable-line rule:line-length
              tag: 4.5.2@sha256:57df87b68a2ef9ffb7f5fa0335e22e6f08d688f661eb58bb290f5b0753a2361a
            env:
              DB_DRIVER: postgres
              DEFAULT_DOMAIN: &host "ln.pospiech.dev"
              DISABLE_TRACKING_FROM: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
              ENABLE_PERIODIC_VISIT_LOCATE: "true"
              IS_HTTPS_ENABLED: "true"
              PORT: &port 8080
              TIMEZONE: "Europe/Warsaw"
            envFrom:
              - secretRef:
                  name: shlink-secret
              - secretRef:
                  name: shlink-db-secret
      
    service:
      main:
        controller: main
        ports:
          http:
            port: *port

    route:
      main:
        hostnames:
          - *host 
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *port
