---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: jellyfin
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: intel-device-plugin-gpu
      namespace: kube-system
  values:
    defaultPodOptions:
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 44
          - 110
          - 65542 # gladius:external-services
    controllers:
      jellyfin:
        type: statefulset

        containers:
          app:
            image:
              repository: jellyfin/jellyfin
              tag: 10.10.7
            env:
              TZ: Europe/Warsaw

            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              privileged: true
            resources:
              requests:
                gpu.intel.com/i915: 1
              limits:
                gpu.intel.com/i915: 1

    service:
      app:
        controller: jellyfin
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.0.42.103
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: *port

    route:
      app:
        annotations:
          hajimari.io/icon: simple-icons:jellyfin
        hostnames:
          - "tv.pospiech.dev"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        existingClaim: jellyfin

      video:
        type: nfs
        server: nfs.homelab.pospiech.dev
        path: /volume1/video
        advancedMounts:
          jellyfin:
            app:
              - path: /media/common

      porn:
        enabled: true
        type: nfs
        server: nfs.homelab.pospiech.dev
        path: /volume1/Porn
        advancedMounts:
          jellyfin:
            app:
              - path: /media/porn

      media:
        enabled: true
        type: nfs
        server: nas01.internal
        path: /mnt/data/media
        advancedMounts:
          jellyfin:
            app:
              - path: /data/media

      transcode:
        type: emptyDir
        advancedMounts:
          jellyfin:
            app:
              - path: /transcode

      card0:
        type: hostPath
        hostPath: /dev/dri/card0
      renderd128:
        type: hostPath
        hostPath: /dev/dri/renderD128

    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"

    resources:
      requests:
        gpu.intel.com/i915: 1
        memory: 2Gi
      limits:
        gpu.intel.com/i915: 1
        memory: 4Gi
