---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: outline-secret
    template:
      data:
        # App
        # AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY }}"
        # AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_KEY }}"
        # AWS_S3_UPLOAD_BUCKET_URL: "https://{{ .AWS_ENDPOINT }}"
        # AWS_REGION: "{{ .AWS_REGION }}"
        SECRET_KEY: "{{ .SECRET_KEY }}"
        UTILS_SECRET: "{{ .UTILS_SECRET }}"
        
        OIDC_CLIENT_SECRET: "{{ .OUTLINE_OAUTH_CLIENT_SECRET }}" # from authelia
        # Postgres Init
        SMTP_HOST: "smtp-relay.default.svc.cluster.local"
        SMTP_PORT: "25"
        # SMTP_USERNAME: "{{ .SMTP_USERNAME }}"
        # SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
        SMTP_FROM_EMAIL: "no-reply@pospiech.dev"
        SMTP_SECURE: "false"
        DEFAULT_LANGUAGE: pl_PL
        LOG_LEVEL: debug
  dataFrom:
    - extract:
        key: outline
    - extract:
        key: authelia
    - extract:
        key: s3
    - extract:
        key: smtp
    - extract:
        key: oauth

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName outline-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: *secretName
    template:
      type: Opaque
      data:
        DATABASE_URL: '{{ index . "uri" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-outline
