---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crunchy-postgres-operator
spec:
  interval: 10m
  path: ./kubernetes/apps/database/crunchy-postgres/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crunchy-postgres-operator-cluster
spec:
  components:
    - ../../../../components/gatus/tcp
  dependsOn:
    - name: crunchy-postgres-operator
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 10m
  path: ./kubernetes/apps/database/crunchy-postgres/cluster
  postBuild:
    substitute:
      APP: postgres
      GATUS_PORT: "5432"

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crunchy-postgres-operator-secretstore
spec:
  dependsOn:
    - name: crunchy-postgres-operator-cluster
      namespace: database
    - name: external-secrets
      namespace: external-secrets

  interval: 10m
  path: ./kubernetes/apps/database/crunchy-postgres/stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crunchy-postgres-users
spec:
  dependsOn:
    - name: crunchy-postgres-operator-cluster
      namespace: database

  interval: 10m
  path: ./kubernetes/apps/database/crunchy-postgres/users
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true