---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-ssh-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: git-ssh
        group: infrastructure
        url: "tcp://git.pospiech.dev:22"
        interval: 30s
        ui:
          hide-hostname: true
          hide-url: true
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
