---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName cross-seed-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secretName
    template:
      data:
        config.js: |
          module.exports = {
            action: "inject",
            apiKey: "{{.CROSS_SEED_API_KEY}}",
            delay: 30,
            duplicateCategories: false,
            flatLinking: false,
            includeEpisodes: true,
            includeNonVideos: true,
            includeSingleEpisodes: true,
            linkCategory: "cross-seed",
            linkDirs: [
              "/media/Downloads/qbittorrent/complete/cross-seed"
            ],
            linkType: "hardlink",
            matchMode: "strict",
            outputDir: null,
            port: Number(process.env.CROSS_SEED_PORT),
            qbittorrentUrl: "http://qbittorrent.download.svc.cluster.local",
            radarr: [],
            // radarr: [
            //   "http://radarr.download.svc.cluster.local/?apikey="
            // ],
            skipRecheck: true,
            sonarr: [],
            // sonarr: [
            //   "http://sonarr.download.svc.cluster.local/?apikey="
            // ],
            torznab: [],
            // torznab: [
            //     88, // HUNO
            //     89, // OTW
            //     90, // FNP
            // ].map(i => `http://prowlarr.download.svc.cluster.local/$${i}/api?apikey=`),
            useClientTorrents: true
          }
  dataFrom:
    - extract:
        key: cross-seed
