---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authentik
spec:
  dependsOn:
    - name: crunchy-postgres-operator-cluster
      namespace: database
    - name: dragonfly-cluster
      namespace: database
  interval: 30m
  path: ./kubernetes/apps/security/authentik/app
  postBuild:
    substitute:
      APP: *app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: security
  wait: false # no flux ks dependents
  retryInterval: 1m
  timeout: 5m
