---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app excalidraw

spec:
  components:
    - ../../../../components/gatus/external
  interval: 1h
  path: ./kubernetes/apps/default/excalidraw/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: draw
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  retryInterval: 2m
  timeout: 5m