---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cyberchef
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cyberchef
  values:
    controllers:
      cyberchef:
        containers:
          app:
            image:
              repository: ghcr.io/vaskozl/cyberchef-web
              # yamllint disable-line rule:line-length
              tag: 10.19.4@sha256:7a42846641f5593fd138f0cdf842ea9f3bc079b7a870c6584629d5291d7a7f17
            resources:
              limits:
                memory: 50Mi
              requests:
                cpu: 5m
                memory: 5Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        runAsGroup: 568
        runAsNonRoot: true
        runAsUser: 568
        seccompProfile:
          type: RuntimeDefault
      shareProcessNamespace: true

    service:
      app:
        controller: cyberchef
        ports:
          http:
            port: &port 8080

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.pospiech.dev"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
