---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName grafana-admin-secret
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secretName
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        admin-user: "{{.ADMIN_USERNAME}}"
        admin-password: "{{.ADMIN_PASSWORD}}"

  dataFrom:
    - extract:
        key: grafana

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName grafana-secret
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secretName
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{.OIDC_CLIENT_ID}}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{.OIDC_CLIENT_SECRET}}"

  dataFrom:
    - extract:
        key: grafana

# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: &secretName grafana-db-secret
# spec:
#   refreshInterval: 1m
#   secretStoreRef:
#     name: crunchy-pgo-secrets
#     kind: ClusterSecretStore
#   target:
#     name: *secretName
#     template:
#       type: Opaque
#       data:
#         GF_DATABASE_NAME: '{{ index . "dbname" }}'
#         GF_DATABASE_HOST: '{{ index . "host" }}:5432'
#         GF_DATABASE_USER: '{{ index . "user" }}'
#         GF_DATABASE_PASSWORD: '{{ index . "password" }}'
#         GF_DATABASE_SSL_MODE: disable
#         GF_DATABASE_TYPE: postgres
#   dataFrom:
#     - extract:
#         key: postgres-pguser-grafana