---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName grafana-admin-secret
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secretName
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        admin-user: "{{.ADMIN_USERNAME}}"
        admin-password: "{{.ADMIN_PASSWORD}}"

  dataFrom:
    - extract:
        key: grafana

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName grafana-secret
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secretName
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{.OIDC_CLIENT_ID}}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{.OIDC_CLIENT_SECRET}}"

  dataFrom:
    - extract:
        key: grafana
