---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app backlogs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *app
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{.JWT_SECRET}}"
  dataFrom:
    - extract:
        key: simple-backlogs

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName backlogs-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: *secretName
    template:
      type: Opaque
      data:
        DATABASE_URL: '{{ index . "uri" }}'
        DB_HOST: '{{ index . "host" }}'
        DB_PORT: '{{ index . "port" }}'
        DB_USER: '{{ index . "user" }}'
        DB_PASSWORD: '{{ index . "password" }}'
        DB_NAME: '{{ index . "dbname" }}'
        DB_SSL_MODE: disable
        DB_MAX_CONNS: "10"
        DB_MAX_IDLE_CONNS: "5"
        DB_CONN_MAX_LIFETIME: 1h
  dataFrom:
    - extract:
        key: postgres-pguser-pmapp
