---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        # OAUTH
        ENABLE_OAUTH_SIGNUP: "true"
        OAUTH_MERGE_ACCOUNTS_BY_EMAIL: "true"
        OAUTH_PROVIDER_NAME: SSO
        OPENID_PROVIDER_URL: https://auth.pospiech.dev/application/o/open-webui/.well-known/openid-configuration
        OAUTH_SCOPES: openid email profile
        OPENID_REDIRECT_URI: https://chat.pospiech.dev/oauth/oidc/callback
        OAUTH_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: open-webui
