---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app open-webui
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      open-webui:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: v0.6.15@sha256:fda936056184035a71a9ad5ff3721530ff061f16bc3907efb33a3201ba87ccfe
            env:
              AUTOMATIC1111_BASE_URL: http://sdnext:7860/
              AUTOMATIC1111_CFG_SCALE: 2
              AUTOMATIC1111_SAMPLER: DPM++ SDE
              AUTOMATIC1111_SCHEDULER: Karras
              DATA_DIR: /app/backend/data
              ENABLE_IMAGE_GENERATION: true
              ENABLE_OLLAMA_API: true
              ENABLE_OPENAI_API: false
              ENABLE_RAG_WEB_SEARCH: true
              ENABLE_SEARCH_QUERY: true
              ENABLE_WEBSOCKET_SUPPORT: "true"
              IMAGE_GENERATION_ENGINE: automatic1111
              IMAGE_GENERATION_MODEL: dreamshaper_8
              IMAGE_SIZE: 400x400
              IMAGE_STEPS: 8
              OLLAMA_BASE_URL: http://ollama:11434
              RAG_WEB_SEARCH_ENGINE: searxng
              SEARXNG_QUERY_URL: http://searxng:8080/search?q=<query>
              WEBSOCKET_MANAGER: "redis"
              WEBSOCKET_REDIS_URL: redis://open-webui-dragonfly:6379
            envFrom:
              - secretRef:
                  name: *app
            resources:
              requests:
                cpu: 500m
              limits:
                memory: 2Gi
    service:
      app:
        ports:
          http:
            port: &port 8080
    route:
      app:
        hostnames: ["${GATUS_SUBDOMAIN:=${APP}}.pospiech.dev"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https

    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /app/backend/data
