---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: alloy
  values:
    fullnameOverride: alloy
    crds:
      create: false
    alloy:
      configMap:
        create: false
        name: alloy-configmap
        key: config.alloy
      mounts:
        varlog: true
      extraEnv:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      resources:
        requests:
          cpu: 25m
        limits:
          memory: 512Mi
    controller:
      type: daemonset
    serviceMonitor:
      enabled: true

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy-events
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: alloy
  values:
    fullnameOverride: alloy-events
    crds:
      create: false
    alloy:
      configMap:
        create: false
        name: alloy-events-configmap
        key: config-events.alloy
      resources:
        requests:
          cpu: 10m
        limits:
          memory: 256Mi
    controller:
      type: deployment
      replicas: 1
    serviceMonitor:
      enabled: true
