---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app paperless
  namespace: flux-system
spec:
  components:
    - ../../../../components/nfs-scaler
  dependsOn:
    - name: onepassword
      namespace: external-secrets
    - name: crunchy-postgres-operator-cluster
      namespace: database
    - name: dragonfly-cluster
      namespace: database
  interval: 30m
  path: ./kubernetes/apps/default/paperless/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: documents

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false # no flux ks dependents
  retryInterval: 1m
  timeout: 5m
  # https://github.com/bjw-s/home-ops/blob/c4e694eb9af5858ef91a00db022268aeeaf35ba8/kubernetes/main/apps/selfhosted/paperless/app/externalsecret.yaml
