---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret immich-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        REDIS_HOSTNAME: dragonfly.database.svc.cluster.local
        REDIS_DBINDEX: "2"
        IMMICH_CONFIG_FILE: /config/immich.json
        REDIS_URL: "{{ .REDIS_URL }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        TYPESENSE_API_KEY: "{{ .TYPESENSE_API_KEY }}"

  dataFrom:
    - extract:
        key: immich-typesense
    - extract:
        key: immich
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret immich-db-secret
spec:
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        # https://github.com/immich-app/immich/blob/461f2595b50ce7e3e716e8c88d10631a74226301/docs/docs/install/environment-variables.md?plain=1#L73C4-L73C23
        # DB_VECTOR_EXTENSION: pgvector
        DB_DATABASE_NAME: '{{ index . "dbname" }}'
        DB_HOSTNAME: '{{ index . "host" }}'
        DB_USERNAME: '{{ index . "user" }}'
        DB_PASSWORD: '{{ index . "password" }}'

  dataFrom:
    - extract:
        key: postgres-pguser-immich
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret immich-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        immich.json: |
          {
            "ffmpeg": {
              "crf": 23,
              "threads": 0,
              "preset": "ultrafast",
              "targetVideoCodec": "h264",
              "acceptedVideoCodecs": ["h264"],
              "targetAudioCodec": "aac",
              "acceptedAudioCodecs": ["aac", "mp3", "libopus"],
              "targetResolution": "720",
              "maxBitrate": "0",
              "bframes": -1,
              "refs": 0,
              "gopSize": 0,
              "npl": 0,
              "temporalAQ": false,
              "cqMode": "auto",
              "twoPass": false,
              "preferredHwDevice": "auto",
              "transcode": "required",
              "tonemap": "hable",
              "accel": "disabled"
            },
            "job": {
              "backgroundTask": {
                "concurrency": 5
              },
              "smartSearch": {
                "concurrency": 2
              },
              "metadataExtraction": {
                "concurrency": 5
              },
              "faceDetection": {
                "concurrency": 2
              },
              "search": {
                "concurrency": 5
              },
              "sidecar": {
                "concurrency": 5
              },
              "library": {
                "concurrency": 5
              },
              "migration": {
                "concurrency": 5
              },
              "thumbnailGeneration": {
                "concurrency": 5
              },
              "videoConversion": {
                "concurrency": 1
              }
            },
            "logging": {
              "enabled": true,
              "level": "log"
            },
            "machineLearning": {
              "enabled": true,
              "url": "http://immich-ml.media.svc.cluster.local:3003",
              "clip": {
                "enabled": true,
                "modelName": "ViT-B-32__openai"
              },
              "facialRecognition": {
                "enabled": true,
                "modelName": "buffalo_l",
                "minScore": 0.7,
                "maxDistance": 0.6,
                "minFaces": 3
              }
            },
            "map": {
              "enabled": true,
              "lightStyle": "https://tiles.immich.cloud/v1/style/light.json",
              "darkStyle": "https://tiles.immich.cloud/v1/style/dark.json"
            },
            "reverseGeocoding": {
              "enabled": true
            },
            "oauth": {
              "enabled": true,
              "issuerUrl": "https://id.pospiech.dev/.well-known/openid-configuration",
              "clientId": "{{ .IMMICH_CLIENT_ID }}",
              "clientSecret": "{{ .IMMICH_CLIENT_SECRET }}",
              "scope": "openid email profile groups",
              "signingAlgorithm": "RS256",
              "storageLabelClaim": "preferred_username",
              "storageQuotaClaim": "immich_quota",
              "defaultStorageQuota": 0,
              "buttonText": "Login with PocketID",
              "autoRegister": true,
              "autoLaunch": true,
              "mobileOverrideEnabled": false,
              "mobileRedirectUri": ""
            },
            "passwordLogin": {
              "enabled": false
            },
            "storageTemplate": {
              "enabled": true,
              "hashVerificationEnabled": true,
              "template": "{{"{{"}}y{{"}}"}}/{{"{{"}}MM{{"}}"}}/{{"{{"}}filename{{"}}"}}"
            },
            "image": {
              "thumbnail": {
                "format": "webp",
                "size": 250,
                "quality": 80
              },
              "preview": {
                "format": "jpeg",
                "size": 1440,
                "quality": 80
              },
              "colorspace": "p3",
              "extractEmbedded": false
            },
            "newVersionCheck": {
              "enabled": true
            },
            "trash": {
              "enabled": true,
              "days": 30
            },
            "theme": {
              "customCss": ""
            },
            "user": {
              "deleteDelay": 7
            },
            "library": {
              "scan": {
                "enabled": true,
                "cronExpression": "0 0 * * *"
              },
              "watch": {
                "enabled": false
              }
            },
            "server": {
              "externalDomain": "https://photos.pospiech.dev",
              "loginPageMessage": "Welcome to Home photos app"
            }
          }

  dataFrom:
    - extract:
        key: oauth