---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: immich
  values:
    defaultPodOptions:
      automountServiceAccountToken: false

    controllers:
      immich:
        type: deployment
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: immich

        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: &version v2.0.0
            envFrom: &envFrom
              - secretRef:
                  name: immich-secret
              - secretRef:
                  name: immich-db-secret
              - configMapRef:
                  identifier: config

            resources:
              requests:
                cpu: 100m
                memory: 512M
              limits:
                memory: 1Gi

      ml:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: *version

            envFrom: *envFrom

            resources:
              requests:
                memory: 2150M
              limits:
                memory: 8Gi

    service:
      immich:
        controller: immich
        ports:
          http:
            port: &port 2283
      ml:
        controller: ml
        ports:
          http:
            port: 3003

    configMaps:
      config:
        data:
          DB_PORT: "5432"

          IMMICH_MACHINE_LEARNING_URL: http://immich-ml.media.svc.cluster.local:3003
          IMMICH_SERVER_URL: http://immich.media.svc.cluster.local:3001
          TYPESENSE_HOST: immich-typesense.media.svc.cluster.local

          LOG_LEVEL: verbose
          NODE_ENV: production

    route:
      app:
        hostnames:
          - "photos.pospiech.dev"
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: immich
                port: *port

    persistence:
      config:
        name: immich-config
        type: secret
        advancedMounts:
          immich:
            app:
              - path: /config
      downloads:
        type: nfs
        server: nas01.internal
        path: /mnt/data/apps/immich
        advancedMounts:
          immich:
            app:
              - path: /usr/src/app/upload

      geocoding-dump:
        type: emptyDir
        advancedMounts:
          immich:
            app:
              - path: /usr/src/app/.reverse-geocoding-dump
      geoname-dump:
        type: emptyDir
        advancedMounts:
          immich:
            app:
              # yamllint disable-line rule:line-length
              - path: /usr/src/app/node_modules/local-reverse-geocoder/geonames_dump
      transformers-cache:
        type: emptyDir
        advancedMounts:
          immich:
            app:
              - path: /usr/src/app/.transformers_cache
      model-cache:
        type: emptyDir
        advancedMounts:
          ml:
            app:
              - path: /cache
