# https://github.com/samip5/k8s-cluster/blob/main/k8s/nebula/apps/default/immich/app/hr.yaml
---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-typesense
  namespace: flux-system
spec:
  targetNamespace: &ns media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: onepassword
      namespace: external-secrets
    - name: dragonfly-cluster
      namespace: database
    - name: crunchy-postgres-operator-cluster
      namespace: database
  path: ./kubernetes/apps/media/immich/typesense
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi

---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich
  namespace: flux-system
spec:
  targetNamespace: &ns media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: immich-typesense
    - name: crunchy-postgres-operator-cluster
      namespace: database
    - name: dragonfly-cluster
      namespace: database
  path: ./kubernetes/apps/media/immich/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: photos

# https://github.com/samip5/k8s-cluster/blob/main/k8s/nebula/apps/default/immich/app/hr.yaml
