# https://github.com/samip5/k8s-cluster/blob/main/k8s/nebula/apps/default/immich/app/hr.yaml
---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-typesense
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: onepassword
      namespace: external-secrets
    - name: dragonfly-cluster
      namespace: database
    - name: crunchy-postgres-operator-cluster
      namespace: database
  interval: 30m
  path: ./kubernetes/apps/media/immich/typesense
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false # no flux ks dependents
  retryInterval: 1m
  timeout: 5m

---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich
spec:
  components:
    - ../../../../components/nfs-scaler
  dependsOn:
    - name: immich-typesense
    - name: crunchy-postgres-operator-cluster
      namespace: database
    - name: dragonfly-cluster
      namespace: database
  interval: 30m
  path: ./kubernetes/apps/media/immich/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: photos
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
  retryInterval: 1m
  timeout: 5m
  # https://github.com/samip5/k8s-cluster/blob/main/k8s/nebula/apps/default/immich/app/hr.yaml
