---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app wheel

spec:
  components:
    - ../../../../components/gatus/external
  dependsOn:
    - name: onepassword
      namespace: external-secrets
  interval: 30m
  path: ./kubernetes/apps/default/wheel/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: wheel
      GATUS_PATH: /health

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
  retryInterval: 1m
  timeout: 5m