---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app volsync
spec:
  components:
    - ../../../../components/nfs-scaler
  dependsOn:
    - name: openebs
      namespace: openebs-system
    - name: snapshot-controller
      namespace: kube-system
  interval: 1h
  path: ./kubernetes/apps/volsync-system/volsync/app
  postBuild:
    substitute:
      APP: *app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: volsync-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: volsync-system
  retryInterval: 2m
  timeout: 5m
