---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app backlogs

spec:
  components:
    - ../../../../components/gatus/internal
  dependsOn:
    - name: onepassword
      namespace: external-secrets
    - name: crunchy-postgres-operator-cluster
      namespace: database
  interval: 30m
  path: ./kubernetes/apps/default/backlogs/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: projects

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
  retryInterval: 1m
  timeout: 5m