---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation

components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./home-assistant/ks.yaml
  - ./node-red/ks.yaml
  - ./zigbee2mqtt/ks.yaml
