---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ollama

spec:
  components:
    - ../../../../components/volsync
  interval: 1h
  path: ./kubernetes/apps/llm/ollama/app
  postBuild:
    substitute:
      APP: *app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: llm
  wait: false
  retryInterval: 2m
  timeout: 5m