---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: internal-external-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: internal-external-dns-secret
    template:
      data:
        UNIFI_API_KEY: "{{ .api_key }}"
  dataFrom:
    - extract:
        key: unifi
