---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: victoria-logs
spec:
  interval: 1h
  provider: generic
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-single
  ref:
    semver: 0.x
