---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app node-red
  namespace: flux-system
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: vernemq
      namespace: database
  interval: 30m
  path: ./kubernetes/apps/home-automation/node-red/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: nodered
      VOLSYNC_CAPACITY: 20Gi

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: home-automation
  wait: false
  retryInterval: 1m
  timeout: 5m
