---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vernemq-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: vernemq-auth-secret
    template:
      data:
        # DOCKER_VERNEMQ_VMQ_WEB_UI__ADMIN__USER_NAME: '{{ .ADMIN_USERNAME }}'
        # DOCKER_VERNEMQ_VMQ_WEB_UI__ADMIN__USER_PWD: '{{ .ADMIN_PASSWORD }}'
        DOCKER_VERNEMQ_USER_ADMIN: '{{ .MQTT_USERNAME }}'
        DOCKER_VERNEMQ_USER_HASS-IO: '{{ .MQTT_PASSWORD }}'
  dataFrom:
    - extract:
        key: emqx