---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vernemq
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: vernemq
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *app :
        type: statefulset
        strategy: RollingUpdate
        replicas: 2

        annotations:
          secret.reloader.stakater.com/reload: vernemq-auth-secret

        pod:
          securityContext:
            runAsUser: 10000
            runAsNonRoot: true

        containers:
          app:
            image:
              repository: docker.io/vernemq/vernemq
              tag: 2.1.1-alpine
            env:
              MY_POD_NAME:
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              DOCKER_VERNEMQ_ACCEPT_EULA: 'yes'
              DOCKER_VERNEMQ_DISCOVERY_KUBERNETES: '1'
              DOCKER_VERNEMQ_KUBERNETES_LABEL_SELECTOR: 'app.kubernetes.io/name=vernemq'
              DOCKER_VERNEMQ_LEVELDB__MAXIMUM_MEMORY: '10485760' # in bytes
              DOCKER_VERNEMQ_LEVELDB__WRITE_BUFFER_SIZE_MIN: '1048576'
              DOCKER_VERNEMQ_LEVELDB__WRITE_BUFFER_SIZE_MAX: '2097152'
              # allow clients to failover when pods are restarting
              DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT: 'on'
              DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT: 'on'
              DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT: 'on'
              DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT: 'on'
            envFrom:
              - secretRef:
                  name: vernemq-auth-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health/ping
                    port: &http 8888
                  periodSeconds: 10
                  timeoutSeconds: 5
              readiness: *probes
              startup:
                <<: *probes
                spec:
                  exec:
                    command:
                      # vernemq immediately reports healthy, even before retained messages are replicated
                      # so we need to make sure all nodes have the same num_replicated on startup
                      # see https://github.com/vernemq/docker-vernemq/issues/255
                      - /bin/sh
                      - -c
                      - >-
                        curl -s localhost:8888/status.json |
                        jq -e '.[0] | [to_entries.[].value.num_retained] | .[0] as $x | all(.[]; . == $x)'
                  periodSeconds: 10
                  timeoutSeconds: 5
            resources:
              requests:
                cpu: 20m
                memory: 128Mi
              limits:
                memory: 384Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL

        serviceAccount:
          identifier: *app

    defaultPodOptions:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - *app
                topologyKey: kubernetes.io/hostname

    service:
      app:
        type: LoadBalancer
        sessionAffinity: ClientIP # vernemq docs note that hopping between pods causes a significate data replication/sync cost
        annotations:
          external-dns.alpha.kubernetes.io/hostname: 'mqtt.pospiech.dev.'
          lbipam.cilium.io/ips: 10.0.42.102
        ports: &ports
          mqtt:
            port: 1883
          ws:
            port: 8080
      headless:
        forceRename: '{{ .Release.Name }}' # TODO: Fix this when app-template 4.1.0 is released
        publishNotReadyAddresses: true
        clusterIP: None
        ports: *ports
      http:
        ports:
          http:
            port: *http

    route:
      app:
        hostnames:
          - '{{ .Release.Name }}.pospiech.dev'
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - matches:
              - path:
                  value: /status.json
            backendRefs: &backendRefs
              - identifier: http
                port: *http
          - matches:
              - path:
                  type: PathPrefix
                  value: /status
            backendRefs: *backendRefs
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs: *backendRefs
            filters:
              - type: URLRewrite
                urlRewrite:
                  path:
                    type: ReplacePrefixMatch
                    replacePrefixMatch: /status
        # annotations:
        #   gethomepage.dev/enabled: 'true'
        #   gethomepage.dev/name: VerneMQ
        #   gethomepage.dev/group: Infrastructure
        #   gethomepage.dev/icon: mqtt.svg

    persistence:
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /vernemq/data
            subPath: data
          - path: /vernemq/log
            subPath: log
          - path: /tmp
            subPath: tmp

    serviceMonitor:
      app:
        serviceName: '{{ .Release.Name }}-http'
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 10s
            scrapeTimeout: 1s

    serviceAccount:
      *app : {}

    rbac:
      roles:
        *app :
          type: Role
          rules:
            - apiGroups:
                - ''
              resources:
                - pods
              verbs:
                - get
                - list
            - apiGroups:
                - apps
              resources:
                - statefulsets
              verbs:
                - get
      bindings:
        *app :
          type: RoleBinding
          roleRef:
            identifier: *app
          subjects:
            - identifier: *app
