---
originRequest:
  originServerName: external.pospiech.dev
  http2Origin: true

ingress:
  - hostname: "*.pospiech.dev"
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "pospiech.dev"
    service: *svc
  - hostname: "prywatna-notatka.pl"
    service: *svc
  - hostname: "*.prywatna-notatka.pl"
    service: *svc
  - service: http_status:403
