---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app qbittorrent

spec:
  components:
    - ../../../../components/gatus/internal
    - ../../../../components/volsync
    - ../../../../components/nfs-scaler
  dependsOn:
    - name: onepassword
      namespace: external-secrets
  interval: 30m
  path: ./kubernetes/apps/download/qbittorrent/app
  postBuild:
    substitute:
      APP: *app

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: download
  wait: false
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app qbittorrent-tools
  namespace: download
spec:
  interval: 1h
  path: ./kubernetes/apps/download/qbittorrent/tools
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: download
  wait: false

  retryInterval: 2m
  timeout: 5m