---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flarebypasser
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: flarebypasser
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # https://github.com/lucas-dclrcq/homelabitty/blob/main/kubernetes/apps/downloads/flarebypasser/app/helmrelease.yaml
    controllers:
      flarebypasser:
        containers:
          app:
            image:
              repository: ghcr.io/yoori/flare-bypasser
              tag: v0.1.53
            env:
              UNUSED: "false"

              # requests:
              #   cpu: 10m
              #   memory: 150Mi
              # limits:
              #   memory: 500Mi
    service:
      app:
        controller: flarebypasser
        ports:
          http:
            port: 8191
            targetPort: 8080
