---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app memos
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      memos:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/usememos/memos
              tag: 0.24.4
            env:
              TZ: "Europe/Warsaw"
              MEMOS_PORT: "5230" # https://github.com/usememos/memos/issues/1782
              MEMOS_DRIVER: postgres
              MEMOS_DSN:
                valueFrom:
                  secretKeyRef:
                    name: memos-db-secret
                    key: POSTGRES_URL
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 25m
                memory: 105M
              limits:
                memory: 105M
    service:
      app:
        controller: memos
        ports:
          http:
            port: &port 5230
            appProtocol: http
      grpc:
        controller: memos
        ports:
          http:
            port: 5231
            targetPort: &grpcPort 5230
            appProtocol: kubernetes.io/h2c
    route: {}
      # disable until support for headers matches is enabled
      # app:
      #   annotations:
      #     hajimari.io/icon: mdi:notebook-edit-outline
      #   hostnames:
      #     - &host "{{ .Release.Name }}.pospiech.dev"
      #   parentRefs:
      #     - name: external
      #       namespace: kube-system
      #       sectionName: https
      #   rules:
      #     - backendRefs:
      #         - identifier: app
      #           port: *port
      #     - backendRefs:
      #         - identifier: grpc
      #           port: *grpcPort
      #       matches:
      #         - headers:
      #             - type: Exact
      #               name: Content-Type
      #               value: "application/grpc-web+proto"


    persistence:
      data:
        existingClaim: memos
        globalMounts:
          - path: /var/opt/memos