---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret paperless-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {
            "openid_connect": {
              "APPS": [
                {
                  "provider_id": "sso",
                  "name": "SSO",
                  "client_id": "{{ .OIDC_CLIENT_ID }}",
                  "secret": "{{ .OIDC_CLIENT_SECRET }}",
                  "settings": {
                    "server_url": "https://auth.pospiech.dev/application/o/paperless/.well-known/openid-configuration"
                  }
                }
              ],
              "SCOPE": ["openid","profile","email","groups"]
            }
          }

        # DB setup
        PAPERLESS_DBENGINE: postgresql
        PAPERLESS_DBPORT: "5432"

  dataFrom:
    - extract:
        key: paperless

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName paperless-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: *secretName
    template:
      type: Opaque
      data:
        PAPERLESS_DBNAME: '{{ index . "dbname" }}'
        PAPERLESS_DBHOST: '{{ index . "host" }}'
        PAPERLESS_DBUSER: '{{ index . "user" }}'
        PAPERLESS_DBPASS: '{{ index . "password" }}'

  dataFrom:
    - extract:
        key: postgres-pguser-paperless