apiVersion: v1
kind: PersistentVolume
metadata:
    name: paperless-nfs
spec:
    storageClassName: paperless-nfs
    capacity:
        # Size does not matter
        storage: 1Mi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
        server: nfs.homelab.pospiech.dev
        path: /volume1/apps/paperless
    # Note: The first two options are strictly for NFSv4.2
    mountOptions:
        - nfsvers=4.1
        - nconnect=8
        - hard
        - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: paperless-nfs
    namespace: default
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: paperless-nfs
    resources:
        requests:
            # Size does not matter
            storage: 1Mi
