---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hass
spec:
  secretName: "hass-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "home.pospiech.dev"
  dnsNames:
    - "home.pospiech.dev"
    - "hass-svc.pospiech.dev"
    - "public.pospiech.dev"
