---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secretName hass-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: *secretName
    template:
      type: Opaque
      data:
        HASS_POSTGRES_URL: '{{ index . "uri" }}'
        HASS_POSTGRESQL_CONNECTION_STRING: '{{ index . "uri" }}'
        POSTGRES_HOST: '{{ index . "host" }}'

        POSTGRES_URL: '{{ index . "uri" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-hass-db

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "hass-tls"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      engineVersion: v2
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .TLS_CRT }}"
        tls.key: "{{ .TLS_KEY }}"
  dataFrom:
    - extract:
        key: pospiech-dev-tls
        decodingStrategy: Base64
      rewrite:
        - regexp:
            source: "(.*).crt"
            target: "TLS_CRT"
        - regexp:
            source: "(.*).key"
            target: "TLS_KEY"