---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hass-code-gatus-ep
  namespace: monitoring
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "hass-code-dns"
        group: guarded
        url: 1.1.1.1
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: "hass-code.pospiech.dev"
          query-type: A
        conditions:
          - "len([BODY]) == 0"
        alerts:
          - type: pushover

      - name: "hass-code"
        group: internal
        url: "https://hass-code.pospiech.dev/"
        interval: 1m
        client:
          dns-resolver: tcp://192.168.100.1:53
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
