---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "multus-iot",
              "namespace": "network",
              "ips": ["10.0.42.105/24"],
              "mac": "02:63:11:be:64:a5"
            }
          ]
      securityContext:
        runAsUser: 65534
        runAsGroup: 65533
        fsGroup: 65533
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        # initContainers:
        #   update-ssh-perms:
        #     image:
        #       repository: alpine
        #       tag: latest
        #     command:
        #       - /bin/sh
        #     args:
        #       - -c
        #       - |
        #           cp /ssh-secret/id_rsa /ssh/id_rsa
        #           chmod 0600 /ssh/id_rsa

        pod:
          hostname: "home-assistant"
          nodeSelector:
            kubernetes.io/hostname: goku

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.6.1
            env:
              TZ: Europe/Warsaw
              VENV_FOLDER: /venv

            envFrom:
              - secretRef:
                  name: hass-db-secret

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

          code:
            dependsOn: app
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.103.1@sha256:fc1d8a57dc5ca5fab67999416165d994ab78a7338b046c4b29f168033a6b7b38
            args:
              - --auth
              - none
              - --disable-telemetry
              - --disable-update-check
              - --user-data-dir
              - /config/.vscode
              - --extensions-dir
              - /config/.vscode
              - --port
              - "12321"
              - /config
            env:
              HASS_SERVER: http://localhost:8123

    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: 8123
            primary: true

      code:
        controller: home-assistant
        ports:
          http:
            port: 12321

    route:
      app:
        hostnames:
          - "home.pospiech.dev"
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 8123

      code:
        hostnames:
          - "hass-code.pospiech.dev"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: code
                port: 12321
    rawResources: {}

    persistence:
      config:
        existingClaim: home-assistant
        advancedMounts:
          home-assistant:
            app:
              - path: /config
            code:
              - path: /config

      hass-cache:
        existingClaim: hass-cache
        advancedMounts:
          home-assistant:
            app:
              - path: /venv
                subPath: hass-venv

      backup:
        enabled: true
        type: nfs
        server: nas01.pospiech.dev
        path: /mnt/data/backup/apps/home-assistant
        globalMounts:
          - path: /config/backups

      # ssh-secret:
      #   enabled: true
      #   type: secret
      #   name: hass-ssh-config
      #   defaultMode: 384

      tmpfs:
        type: emptyDir
        advancedMounts:
          home-assistant:
            app:
              - path: /tmp
                subPath: hass-tmp
            code:
              - path: /tmp
                subPath: code-server-tmp
              - path: /nonexistent
                subPath: nonexistent

      # ssh:
      #   type: emptyDir
      #   enabled: true
