---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./ocirepository.yaml
  - ./externalsecret.yaml
  - ./pvc.yaml
  # - ./certificate.yaml
  - ./gatus-code.yaml
  - ./helmrelease.yaml
