---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-v1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rbd-xfs


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-matter-v1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rbd-xfs