---
# yaml-language-server: $schema=https://schemas.bykaj.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app stash
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      stash:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: stashapp/stash
              tag: v0.28.1@sha256:645f6c15b079410d50d488dbeb247c92f25534094dad4e15d886e47648b897f7
            env:
              TZ: "${TIMEZONE}"
              STASH_STASH: "/mnt/private"
              STASH_GENERATED: "/generated"
              STASH_METADATA: "/metadata"
              STASH_CACHE: "/cache"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 9999
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 20m
                memory: 512Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 4000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [44]
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /blobs
            subPath: blobs
          - path: /root/.stash
            subPath: config
          - path: /generated
            subPath: generated
          - path: /metadata
            subPath: metadata
      backups:
        type: nfs
        server: "nas01.internal"
        path: /mnt/data/backup/apps
        globalMounts:
          - path: /mnt/backups
            subPath: stash
      media:
        type: nfs
        server: "nas01.internal"
        path: /mnt/data/media
        globalMounts:
          - path: /mnt/private
      tmpfs:
        type: emptyDir
        advancedMounts:
          stash:
            app:
              - path: /cache
                subPath: cache
              - path: /root/.stash/logs
                subPath: logs
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames:
          - "${GATUS_DOMAIN:=${GATUS_SUBDOMAIN:=${APP}}.pospiech.dev"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https-app
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port