---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app open-webui

spec:
  components:
    - ../../../../components/dragonfly
    - ../../../../components/gatus/external
    - ../../../../components/volsync
  dependsOn:
    - name: crunchy-postgres-operator
      namespace: database
    - name: dragonfly
      namespace: database
    - name: searxng
  interval: 1h
  path: ./kubernetes/apps/llm/open-webui/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: chat
      VOLSYNC_CAPACITY: 10Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: llm
  wait: false
  healthCheckExprs:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      failed: status.phase != 'ready'
      current: status.phase == 'ready'
  retryInterval: 2m
  timeout: 5m