---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smartctl-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: smartctl-exporter
  values:
    fullnameOverride: *app
    serviceMonitor:
      enabled: true
      relabelings:
        - action: labeldrop
          regex: (pod)
        - action: replace
          regex: (.*)
          replacement: $1.internal
          sourceLabels:
            - __meta_kubernetes_endpoint_node_name
          targetLabel: instance
    prometheusRules:
      enabled: false
