---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app serpbear
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: serpbear
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      serpbear:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            fsGroup: 1001
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: towfiqi/serpbear
              tag: 3.1.0
            env:
              NEXT_PUBLIC_APP_URL: "https://serpbear.pospiech.dev"
            envFrom:
              - secretRef:
                  name: *app
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 3000
                  initialDelaySeconds: 10
                  periodSeconds: 30
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  failureThreshold: 3
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - "serpbear.pospiech.dev"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/data
