---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app opengist
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: onepassword
      namespace: external-secrets
  interval: 30m
  path: ./kubernetes/apps/default/opengist/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 2Gi
      # VOLSYNC_STORAGECLASS: ceph-block # default
      # VOLSYNC_SNAPSHOTCLASS: csi-ceph-block # update with storageclass
      # VOLSYNC_COPY_METHOD: Snapshot # default; change to "Clone" for local-path
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
  retryInterval: 1m
  timeout: 5m
