---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 75m
  chartRef:
    kind: OCIRepository
    name: vault
  values:
    metrics:
      enabled: true
    service:
      enabled: true

    server:
      extraLabels:
        configmap.reloader.stakater.com/reload: auto

      readinessProbe:
        enabled: true
        path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
      livenessProbe:
        enabled: true
        path: "/v1/sys/health?standbyok=true"
        initialDelaySeconds: 60

      # extraEnvironmentVars is a list of extra environment variables to set with the stateful set. These could be
      # used to include variables required for auto-unseal.
      extraEnvironmentVars:
        VAULT_CACERT: /vault/userconfig/tls-ca/ca.crt
        TZ: Europe/Warsaw

      dataStorage:
        enabled: true
        storageClass: "ceph-block"

      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 256Mi

      standalone:
        enabled: false

      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
          setNodeId: true
        config: |
          ui = true
          cluster_name = "vault"
          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }

          storage "raft" {
            path = "/vault/data"
            retry_join {
              leader_api_addr = "https://vault-0:8200"
            }
            retry_join {
              leader_api_addr = "https://vault-1:8200"
            }
            retry_join {
              leader_api_addr = "https://vault-2:8200"
            }
          }

    ui:
      enabled: true
      serviceType: "ClusterIP"

    injector:
      enabled: "false"
