---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-typesense
  namespace: media
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: immich-typesense
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/arch: amd64

    controllers:
      immich-typesense:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/typesense/typesense
              tag: 0.25.2
            env:
              TYPESENSE_DATA_DIR: /data
            envFrom:
            - secretRef:
                name: immich-typesense
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8108
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 60
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
    service:
      app:
        controller: immich-typesense
        ports:
          http:
            port: *port

    persistence:
      data:
        existingClaim: immich-typesense
