---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app zigbee2mqtt
  namespace: flux-system
spec:
  components:
    - ../../../../components/gatus/internal
    - ../../../../components/volsync
  dependsOn:
    - name: vernemq
      namespace: database
    - name: onepassword
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  path: ./kubernetes/apps/home-automation/zigbee2mqtt/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: zigbee
      # VOLSYNC_ACCESSMODES: ReadWriteMany
      # VOLSYNC_STORAGECLASS: openebs-hostpath
      # VOLSYNC_SNAPSHOTCLASS: openebs-hostpath

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: home-automation
  wait: false
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zigbee2mqtt-exporter
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/home-automation/zigbee2mqtt/exporter"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: home-automation
  wait: false
