---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: fluent-bit
spec:
  interval: 1h
  provider: generic
  url: oci://ghcr.io/fluent/helm-charts/fluent-bit
  ref:
    semver: 0.x
