---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pocket-id
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: pocket-id
  values:
    controllers:
      pocket-id:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app

        containers:
          app:
            image:
              repository: ghcr.io/pocket-id/pocket-id
              tag: v1.11.2

            env:
              ANALYTICS_DISABLED: "true"
              APP_URL: https://id.pospiech.dev
              DB_CONNECTION_STRING: file:/app/data/pocket-id.db?_journal_mode=WAL&_busy_timeout=2500&_txlock=immediate
              EMAIL_API_KEY_EXPIRATION_ENABLED: true
              EMAIL_LOGIN_NOTIFICATION_ENABLED: true
              EMAIL_ONE_TIME_ACCESS_AS_ADMIN_ENABLED: true
              SESSION_DURATION: 1440
              SMTP_FROM: pocket-id@pospiech.dev
              SMTP_HOST: smtp-relay.default.svc.cluster.local
              SMTP_PORT: 25
              TRUST_PROXY: true
              TZ: Europe/Warsaw
              UI_CONFIG_DISABLED: true
              UPLOAD_PATH: /app/data/uploads
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

            resources:
              requests:
                memory: 250M
                cpu: 10m
              limits:
                memory: 400M

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        ports:
          http:
            port: 1411

    route:
      app:
        hostnames:
          - "id.pospiech.dev"
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https

    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /app/data

      var:
        type: emptyDir
        sizeLimit: 1Gi
