---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secret.yaml
  - replicationdestination.yaml
  # do not create replication source during migration
  # - replicationsource.yaml
