---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname vernemq

spec:
  components:
    # - ../../../../components/gatus/external
    - ../../../../components/gatus/tcp
  dependsOn:
    - name: onepassword
      namespace: external-secrets
  interval: 30m
  path: "./kubernetes/apps/database/vernemq/app"
  postBuild:
    substitute:
      APP: *appname
      GATUS_PORT: "1883"
      GATUS_SUBDOMAIN: mqtt

  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: false
  timeout: 5m