---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  annotations:
    external-dns.alpha.kubernetes.io/target: "external.pospiech.dev"
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: "10.0.42.199"
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "external.pospiech.dev"
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.pospiech.dev"
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.pospiech.dev"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: pospiech-dev-tls
    - name: privnote-https
      protocol: HTTPS
      port: 443
      hostname: "prywatna-notatka.pl"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: prywatna-notatka-pl-tls
